 -- Create the Rooms table
SQL> CREATE TABLE rooms (
  2      room_number NUMBER PRIMARY KEY,
  3      category VARCHAR2(50),
  4      price NUMBER(10, 2),
  5      is_available NUMBER(1) DEFAULT 1 -- 1 means Available, 0 means Booked
  6  );
SQL> -- Create the Bookings table
SQL> CREATE TABLE bookings (
  2      booking_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  3      customer_name VARCHAR2(100),
  4      room_number NUMBER,
  5      booking_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  6      CONSTRAINT fk_room FOREIGN KEY (room_number) REFERENCES rooms(room_number)
  7  );
SQL> -- Insert Dummy Data
SQL> INSERT INTO rooms (room_number, category, price, is_available) VALUES (101, 'Standard', 100, 1);

SQL> INSERT INTO rooms (room_number, category, price, is_available) VALUES (102, 'Standard', 100, 1);

SQL> INSERT INTO rooms (room_number, category, price, is_available) VALUES (201, 'Deluxe', 200, 1);


SQL> INSERT INTO rooms (room_number, category, price, is_available) VALUES (301, 'Suite', 500, 1);

SQL> COMMIT;

SQL> select * from rooms;